#ifndef LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_H
#define LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_H

#include <string>

// Main
int lengthOfLongestSubstring(std::string s);

#endif // LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS_H
